### PR TITLE
Fix out-of-source build, distcheck, and revert the behavior of autogen.sh

### PR DESCRIPTION
**Pull request by lantw44**
- `autogen.sh` now run `configure` automatically. It can be disabled by setting `NOCONFIGURE=1` before running `autogen.sh`.
- Add a missing macro file for `libsecp25k1`.
- Commits pulled from bitcoin upstream are used to fix out-of-source build for `leveldb`.

### CODE REVIEW

**Comment by zhouer** [comment]
@lantw44: .travis.yml 的 75 ~ 77 行是之前被我註解掉的，因為 configure 時會失敗，
能不能麻煩您把失敗的原因釐清，一併處理，謝謝！

**Comment by lantw44** [comment]
直接把註解拿掉了，我猜以前的狀況應該跟 dist 或 distcheck 有關？

**Comment by hihiben** [comment]
pass

**Comment by lbyyy** [comment]
pass

**Pull request merged**
